//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPS_DataEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EPS_GridDBEntities : DbContext
    {
        public EPS_GridDBEntities()
            : base("name=EPS_GridDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EPS_Device> EPS_Device { get; set; }
        public DbSet<EPS_Order> EPS_Order { get; set; }
        public DbSet<EPS_OrderDetails> EPS_OrderDetails { get; set; }
        public DbSet<EPS_OrderLog> EPS_OrderLog { get; set; }
        public DbSet<EPS_PollutionSource> EPS_PollutionSource { get; set; }
        public DbSet<EPS_SiteData> EPS_SiteData { get; set; }
        public DbSet<EPS_SiteDatahistory> EPS_SiteDatahistory { get; set; }
        public DbSet<EPS_SiteType> EPS_SiteType { get; set; }
        public DbSet<t_menu> t_menu { get; set; }
        public DbSet<t_role> t_role { get; set; }
        public DbSet<t_role_menu> t_role_menu { get; set; }
        public DbSet<t_user> t_user { get; set; }
    }
}
