//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUC_DataEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SUC_SYSContainer : DbContext
    {
        public SUC_SYSContainer()
            : base("name=SUC_SYSContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SUC_AuditOffice> SUC_AuditOffice { get; set; }
        public virtual DbSet<SUC_ClassInfo> SUC_ClassInfo { get; set; }
        public virtual DbSet<SUC_ClaTeaCurAssociative> SUC_ClaTeaCurAssociative { get; set; }
        public virtual DbSet<SUC_Course> SUC_Course { get; set; }
        public virtual DbSet<SUC_CourseType> SUC_CourseType { get; set; }
        public virtual DbSet<SUC_Courseware> SUC_Courseware { get; set; }
        public virtual DbSet<SUC_Machine> SUC_Machine { get; set; }
        public virtual DbSet<SUC_Order> SUC_Order { get; set; }
        public virtual DbSet<SUC_OrderDetails> SUC_OrderDetails { get; set; }
        public virtual DbSet<SUC_OrderLog> SUC_OrderLog { get; set; }
        public virtual DbSet<SUC_UavData> SUC_UavData { get; set; }
        public virtual DbSet<SUC_UavInfo> SUC_UavInfo { get; set; }
        public virtual DbSet<SUC_UavSortieData> SUC_UavSortieData { get; set; }
        public virtual DbSet<SUC_UploadAndAudit> SUC_UploadAndAudit { get; set; }
        public virtual DbSet<t_code_rules> t_code_rules { get; set; }
        public virtual DbSet<t_menu> t_menu { get; set; }
        public virtual DbSet<t_role_menu> t_role_menu { get; set; }
        public virtual DbSet<t_roles> t_roles { get; set; }
        public virtual DbSet<t_user> t_user { get; set; }
        public virtual DbSet<SUC_Site> SUC_Site { get; set; }
        public virtual DbSet<v_ClaTeaCurAssociative> v_ClaTeaCurAssociative { get; set; }
        public virtual DbSet<v_SUC_Courseware> v_SUC_Courseware { get; set; }
        public virtual DbSet<v_user> v_user { get; set; }
        public virtual DbSet<V_SortiePatition> V_SortiePatition { get; set; }
    }
}
