//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUC_DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUC_Machine
    {
        public System.Guid MachineId { get; set; }
        public string UavSerialNO { get; set; }
        public string MachineName { get; set; }
        public string MachineCode { get; set; }
        public string MachineTypeCode { get; set; }
        public string EngineState { get; set; }
        public string ElectricQuantity { get; set; }
        public string StructureCommence { get; set; }
        public string CuttingCapacity { get; set; }
        public string PropellerAvailability { get; set; }
        public string OverallEvaluationBuild { get; set; }
        public string MachinePicture { get; set; }
        public int Disabled { get; set; }
        public string Remark { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
    }
}
