//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUC_DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUC_ClassInfo
    {
        public System.Guid ClassInfoId { get; set; }
        public string ClassCode { get; set; }
        public string ClassName { get; set; }
        public int Disabled { get; set; }
        public string Remark { get; set; }
        public System.DateTime Rec_CreateTime { get; set; }
        public string Rec_CreateBy { get; set; }
        public Nullable<System.DateTime> Rec_ModifyTime { get; set; }
        public string Rec_ModifyBy { get; set; }
    }
}
