//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUC_DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUC_UavInfo
    {
        public System.Guid UavInfoId { get; set; }
        public string UavSerialNO { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
        public string Sortie { get; set; }
        public string VideoAddr { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string Altitude { get; set; }
        public Nullable<decimal> Temperature { get; set; }
        public Nullable<decimal> Humidity { get; set; }
        public string Speed { get; set; }
        public string AtmosPressure { get; set; }
        public Nullable<int> UavState { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Disabled { get; set; }
        public Nullable<System.DateTime> Rec_CreateTime { get; set; }
        public string Rec_CreateBy { get; set; }
        public Nullable<System.DateTime> Rec_ModifyTime { get; set; }
        public string Rec_ModifyBy { get; set; }
    }
}
