//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUC_DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_user
    {
        public string UserId { get; set; }
        public string UserCode { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public string DepNo { get; set; }
        public string Email { get; set; }
        public string IsAdmin { get; set; }
        public string Sex { get; set; }
        public string Telephone { get; set; }
        public string Addr { get; set; }
        public string UserRoles { get; set; }
        public string Remark { get; set; }
        public int Disabled { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
    }
}
