//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUC_DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ClaTeaCurAssociative
    {
        public System.Guid ClaTeaCurAssociativeId { get; set; }
        public string ClaTeaCurAssociativeCode { get; set; }
        public string SchoolSmester { get; set; }
        public string CourseCode { get; set; }
        public string CourseName { get; set; }
        public string UserCode { get; set; }
        public string UserName { get; set; }
        public string ClassCode { get; set; }
        public string ClassName { get; set; }
        public string AuditOfficeCode { get; set; }
        public string AuditOfficeName { get; set; }
        public string CourseTypeCode { get; set; }
        public string CourseTypeName { get; set; }
        public int Disabled { get; set; }
    }
}
