//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUC_DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SortiePatition
    {
        public System.Guid UavInfoId { get; set; }
        public string UavSerialNO { get; set; }
        public string Sortie { get; set; }
        public string VideoAddr { get; set; }
        public Nullable<System.DateTime> Rec_CreateTime { get; set; }
        public Nullable<System.DateTime> CreatTimeMax { get; set; }
    }
}
